### ISSUE TITLE
Chronology of Dropdown/Fists Weapon

### ISSUE THREAD

**Issue by wilsooooooooon** [wotv-tools/wotv-tools.github.io#3]
Not a big issue at all, but is there a way to better organize the dropdown menu for the equipment Calc? It seems very random right now. I would suggest something like this list below. Thanks! 

WEAPONS
Axe
Bow
Dagger
Fists (instead of Melee)
Greatsword
Gun
Katana
Mace
Ninja Blade
Shield
Spear
Staff
Sword

OTHERS
Armor
Clothing
Hat
Helm
Accessory

**Comment by wotv-tools** [comment]
Thanks for the suggestion. I have renamed Melee to Fist. As for the ordering, sorry about the confusion! I didn't realize my grouping was placed in the wrong dropdown after my UI revamp. Thanks for bringing this to my attention! This should be fixed now.

**Comment by wilsooooooooon** [comment]
Thanks for fixing this! I was so surprised today when I checked the site again wasn't expecting to get such a quick response!
