### ISSUE TITLE
Coral sword lists Mythril Sword as ingredient, is it wrong?

### ISSUE THREAD

**Issue by phil-ho** [wotv-tools/wotv-tools.github.io#6]
https://wotv-tools.github.io/#eyJjYXRlZ29yeSI6IjIiLCJhcnRpZmFjdCI6IkFGX0xXX1NXT18wMDYiLCJsZXZlbCI6IjUwIn0=

**Comment by wotv-tools** [comment]
It will probably be different when we get closer to the actual release date of the item, but for now the data shows a mythril sword for some reason...

**Comment by wotv-tools** [comment]
With today's update, the Coral Sword is now showing different ingredients.
