### ISSUE TITLE
Coral Sword missing +1 through +5

### ISSUE THREAD

**Issue by swarren83** [wotv-tools/wotv-tools.github.io#9]
Coral Sword does not have +1 through +5 versions available.

**Comment by wotv-tools** [comment]
I am able to see a +1 to +5 version of the Coral Sword. Are you looking under Sword and not Greatsword? Do all the other items load?

**Comment by wotv-tools** [comment]
Here's a [direct link](https://wotv-tools.github.io/#eyJjYXRlZ29yeSI6IjIiLCJhcnRpZmFjdCI6IkFGX0xXX1NXT18wMDZfNSIsImxldmVsIjoiNTAifQ==). Let me know if this doesn't work for you!

**Comment by swarren83** [comment]
I see it now.  I was under sword and must not have refreshed after the change was available.
